package com.example.jetpackcomposebehaviourdemo.Media_Playback_Demo

import android.app.Application
import com.example.jetpackcomposebehaviourdemo.Notification_Demo.NotificationApplication
import dagger.hilt.android.HiltAndroidApp

@HiltAndroidApp
class MediaApp: NotificationApplication()